# Generated by Django 4.1.5 on 2023-01-22 17:46

from django.db import migrations


def populate_status(apps, schemaeditor):
    statuses = {
        "to do": "An issue that has not yet been started",
        "in progress": "An issue in active development",
        "done": "An issue that has been marked as complete"
    }
    Status = apps.get_model("issues", "Status")
    for name, desc in statuses.items():
        status_obj = Status
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
    ]
